### ISSUE TITLE
New business rules

### ISSUE THREAD

**Issue by pmaldonado-espol** [MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA#5]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by pedbvasq** [comment]
Dear Ing @pmaldonado-espol following the 7th step, we notify you that our GitHub is ready to receive your issue ticket.

**Comment by pmaldonado-espol** [comment]
> Dear Ing @pmaldonado-espol following the 7th step, we notify you that our GitHub is ready to receive your issue ticket.

It was sent 5 days ago:
![image](https://user-images.githubusercontent.com/106487843/212987499-79477487-3e62-422a-ba9b-5cd35d3eea3a.png)

**Comment by pedbvasq** [comment]
Dear, customer. We have received  business rule, we will start working.

**Comment by pedbvasq** [comment]
The issue has been categorized.

**Comment by pedbvasq** [comment]
@KevinChevez will be developing the solution, @MargaritaMawyin  will be in charge of Tests. @pedbvasq  will be the analyst.

**Comment by pedbvasq** [comment]
[Impact.analysis.-.issue.6.docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10438790/Impact.analysis.-.issue.6.docx)
Dear customer @pmaldonado-espol, here is the impact analysis. we are waiting for you response.

**Comment by pmaldonado-espol** [comment]
> [Impact.analysis.-.issue.6.docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10438790/Impact.analysis.-.issue.6.docx)
> Dear customer @pmaldonado-espol, here is the impact analysis. we are waiting for you response.

It's OK, go ahead.

**Comment by KevinChevez** [comment]
https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/blob/dc23af0779c4699746350ec978cf6456a65d4393/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L116-L121

I have completed the solution to the indicated issue, please team, verify its functionality.

**Comment by MargaritaMawyin** [comment]
[testing .docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10453105/testing.docx)

Testing done. Two tests have failed @KevinChevez

**Comment by KevinChevez** [comment]
> [testing .docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10453105/testing.docx)
> 
> Testing done. Two tests have failed @KevinChevez

Ok, reviewing the code I found that the error is in the definition of this function. I'm going to correct it, thanks for the warning, and sorry for the inconvenience. @MargaritaMawyin 
https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/blob/dc23af0779c4699746350ec978cf6456a65d4393/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/Customer.java#L43-L44

**Comment by KevinChevez** [comment]
> [testing .docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10453105/testing.docx)
> 
> Testing done. Two tests have failed @KevinChevez

@MargaritaMawyin I have made the corrections to the code, please do the tests and indicate if there is any problem.
https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/blob/adccead792f3a830516ed1bcac7768772e28cb56/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/Customer.java#L43-L45

**Comment by MargaritaMawyin** [comment]
[testing .docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10456724/testing.docx)

Now, all the tests have passed. Everything is all right. @KevinChevez

**Comment by MargaritaMawyin** [comment]
[Acceptance test plan.docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10456944/Acceptance.test.plan.docx)

Dear customer @pmaldonado-espol , I attach the acceptance plan document for your review.

**Comment by pmaldonado-espol** [comment]
> [Acceptance test plan.docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10456944/Acceptance.test.plan.docx)
> 
> Dear customer @pmaldonado-espol , I attach the acceptance plan document for your review.

There is no tests plan included in it document.

**Comment by MargaritaMawyin** [comment]
[Acceptance test plan.docx](https://github.com/Margarita@pmaldonado-espol awyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10459656/Acceptance.test.plan.docx)

Dear customer @pmaldonado-espol , I attach the acceptance testing plan correctly this time.

**Comment by MargaritaMawyin** [comment]
[Acceptance test plan.docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10459672/Acceptance.test.plan.docx)

Dear customer @pmaldonado-espol , I attach the acceptance testing plan correctly this time.

**Comment by pmaldonado-espol** [comment]
> [Acceptance test plan.docx](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10459672/Acceptance.test.plan.docx)
> 
> Dear customer @pmaldonado-espol , I attach the acceptance testing plan correctly this time.

It's OK. Please send the execution instructions for the Acceptance Tests Plan.

**Comment by pedbvasq** [comment]
Dear customer @pmaldonado-espol All the previous steps have been verified and the solution has been completed.
@KevinChevez will release the new software version for you.

**Comment by KevinChevez** [comment]
Dear customer @pmaldonado-espol Here I attach the file to see the installation steps and the use of the new program.
[howToUseTheProgram.pdf](https://github.com/MargaritaMawyin/ISII-WORKSHOPS-SERVICIOS_EN_LINEA/files/10461197/howToUseTheProgram.pdf)

**Comment by pedbvasq** [comment]
Dear customer @pmaldonado-espol Dear customer, are you satisfied with the solution that my colleague has presented? Did you have a problem installing the program with the new changes? If the process is unsatisfactory, please let us know. We are waiting for your response.

**Comment by pmaldonado-espol** [comment]
> Dear customer @pmaldonado-espol Dear customer, are you satisfied with the solution that my colleague has presented? Did you have a problem installing the program with the new changes? If the process is unsatisfactory, please let us know. We are waiting for your response.

No more changes are needed, thank you.

**Comment by pedbvasq** [comment]
@pmaldonado-espol Thank you, we are going to proceed to close the issue.
